stages:
  - build
  - test

build:
    stage: build
    image: registry.forge.orange-labs.fr/swift-server-performances/kituraapi
    script:
        - swift build -c release
    only: 
        - master
    tags:
        - docker
        - shared
        - forge